### ISSUE TITLE
Cannot Compile {1.20.1}

### ISSUE THREAD

**Issue by RulOfficial** [Luke100000/ImmersiveArmors#105]
I have been trying to compile the fork i made of your mod like 2h now, maybe something its outdated ?

**Comment by Luke100000** [comment]
Well, whats the error?

**Comment by RulOfficial** [comment]
After installing git and adding 'cmd' to some commands in the build.gradle, rn its failing to evaluate :common, i thought it can be an issue with the gradle version or the loom version, but that wasnt either.

It says the error is located at: ImmersiveArmors-1.20.1\common\build.gradle (line 22)

**Comment by Luke100000** [comment]
I need the full error in order to help, paste the build log here

**Comment by RulOfficial** [comment]
```
> Configure project :
Architect Plugin: 3.4.154
Architectury Loom: 0.12.0.374
You are using an outdated version of Architectury Loom! This version will not receive any support, please consider updating!

> Configure project :common
architectury's common(Boolean forgeEnabled) is deprecated, use common(String... platforms) instead

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Invite\Downloads\ImmersiveArmors-1.20.1\common\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':common'.
> C:\Users\Invite\Downloads\ImmersiveArmors-1.20.1\common\build\libs\immersive_armors-Microsoft Windows [Versi´┐¢n 10.0.19045.4170](c) Microsoft Corporation. Todos los derechos reservados.C:\Users\Invite\Downloads\ImmersiveArmors-1.20.1>-transformProductionFabric.jar (El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos)

```

**Comment by Luke100000** [comment]
While I don't know whats happening here with the call to git within `getAppVersion()`, in your case I would just manually set the version in the roots `build.gradle` to `version = "dev"`. Or use properties, whatever makes more sense for you.

**Comment by RulOfficial** [comment]
Yeah, that worked perfecly, thanks you.

**Comment by RulOfficial** [comment]
Hey, sorry to bother you again, what im suposed to move into my mod folder?, i have tried 4 different jars and it doesnt work.

**Comment by Luke100000** [comment]
Should be `/fabric/build/libs/immersive-armors-whateverversionyoupicked.jar`. Don't pick the dev-shadow or sources jar.

**Comment by RulOfficial** [comment]
Not working and not rising a crash log either, will try in another pc later.

**Comment by RulOfficial** [comment]
Okay, it seems that using the gradlew.bat doesnt do anything, but if i compile manually i get a corrupted jar that crash the mc upon loading, any idea ?

**Comment by Luke100000** [comment]
Let's start from scratch, how did you compile?

```sh
git clone https://github.com/Luke100000/ImmersiveArmors
cd ImmersiveArmors
chmod +x ./gradlew
./gradlew build
ls ./fabric/build/libs/
```

Works for me in Linux with Java 21 and lists a file `immersive_armors-0-git-3564196.jar`

How do you notice the jar is corrupted?

**Comment by RulOfficial** [comment]
Im in windows, i just dowload the zip, unzip it and click on the gradlew bat, usually if that doesnt work i just cd the folder and use "gradlew build", the mc just do an instant crash and doesnt even rise any log

**Comment by Luke100000** [comment]
And it concluded in
```
BUILD SUCCESSFUL in 35s
30 actionable tasks: 30 executed
```
?

Can you send me the compiled jar please?

**Comment by RulOfficial** [comment]
https://www.mediafire.com/file/akzgrocer9cefcl/immersive_armors-dev.jar/file
I have tried with 3 pc in a row now and its the same,

**Comment by RulOfficial** [comment]
I manage to get the next error message:

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config immersive_armors.mixins.json for mod immersive_armors
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config immersive_armors.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'immersive_armors.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by Luke100000** [comment]
Very interesting. I can confirm that mixin loading broke in recent versions. Probably a change in loom/fabric I need to fix on my end. I will let you know once that works again.

Btw, I made a diff over your jar and it looks like you are not using a recent version. Double-check that you are on the top of your branch.

**Comment by RulOfficial** [comment]
Hmmm how? im a bit confused rn, i am not using a recent version of what ?

**Comment by RulOfficial** [comment]
Btw have u compiled my fork whitout problems in linux ?

**Comment by Luke100000** [comment]
Ohh no sorry, the diff I saw was your fork ^^
No, I didn't explicitely tested your fork yet, but I assume it will work once I fixed whatever is broken in the upstream.

**Comment by RulOfficial** [comment]
Lets hope 🙏🙏🙏

**Comment by Luke100000** [comment]
I updated gradle and loom in the 1.20.1 branch and can now compile again, it should also fix your issues

**Comment by RulOfficial** [comment]
Okay sweet, it worked at least with the fabric version, the forge version dont worked well for me, but maybe its just a bug with Sinytra Connector, thank you very much Luke.
