### ISSUE TITLE
Game crashes before startmenu

### ISSUE THREAD

**Issue by RobbyRotten97** [Luke100000/ImmersiveArmors#14]
So, once i launch minecraft, (having this mod included with others) the game loads as usual, but once the loading bar finish it crashes showing this message error "java.lang.ClassCastException: class net.minecraft.client.renderer.entity.ItemRenderer cannot be cast to class immersive_armors.mixin.MixinItemRenderer (net.minecraft.client.renderer.entity.ItemRenderer is in module minecraft@1.18.2 of loader 'TRANSFORMER' @3f68a7f8; immersive_armors.mixin.MixinItemRenderer is in module immersive_armors@1.3.0 of loader 'TRANSFORMER' @3f68a7f8)

I include as well the crash error txt that comes with the error message.

[crash-2022-04-25_14.12.34-client.txt](https://github.com/Luke100000/ImmersiveArmors/files/8554399/crash-2022-04-25_14.12.34-client.txt)
"

**Comment by Luke100000** [comment]
Thanks for warning me, it's indeed not working outside my IDE.

**Comment by Luke100000** [comment]
I reuploaded 7.3.0, please try again :)
