### ISSUE TITLE
Heavy Armor render Head

### ISSUE THREAD

**Issue by Exokyhh** [Luke100000/ImmersiveArmors#26]
Don't know if it's intentional, but if you equip the heavy armor with a skin that has a hat, it will render "partially", leaving the back of the head empty.
(check my player, the right side is a dummy that has the armor)
![heavy armor](https://user-images.githubusercontent.com/90096585/167029349-8ae713e5-1fd1-4916-90a4-b6055a709cb2.png)

_Forge - 36.2.34 (1.16.5)
immersive-armors-1.1.2-forge.jar_

**Comment by Luke100000** [comment]
Fixed, thanks!

**Comment by Exokyhh** [comment]
Good! What about the mod incompatibilty with first aid? Or the version with this fix, when will you release it? I can't wait to play it! Me and my friends wanted to start to play our modpack this evening, but if you are fixing the issues, I think we will wait for you

**Comment by Luke100000** [comment]
First aid uses it's own armor-damage-handler-thingy and basically ignores the vanilla one (and therefore mine too). I can fix it, but I need to be careful to not break other things instead. It should be done by today, maybe tomorrow.

**Comment by Exokyhh** [comment]
Okay! I got another question tho, I've seen you fixed both the bugs, where (and when) will I be able to download the fixed version of the mod in **1.16.5**? (Sorry if I ask but I'm kinda new to GitHub and I don't know how it works). Thanks in advance 😁

**Comment by Luke100000** [comment]
All versions have been uploaded to CurseForge by now. Please let me know if everything works :)
I did a lot of black magic to resolve the incompatibilities, this might cause new problems.
