### ISSUE TITLE
[Fabric] Incompatibility with cosmetic armor

### ISSUE THREAD

**Issue by Kuggle01** [Luke100000/ImmersiveArmors#28]
Most armors render incorrectly when equpied in the cosmetic slots with this cosmetic armor mod https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric This can range from just 3D elements not rendering like with aquamarine armor or it can be the entire armor rendering incorrectly like with robe armor https://imgur.com/a/9KSoqut

**Comment by Luke100000** [comment]
Fixed, if you have time, please confirm if it is fixed for you
