### ISSUE TITLE
Armors do not load visually (1.16.5)

### ISSUE THREAD

**Issue by Exokyhh** [Luke100000/ImmersiveArmors#30]
The last version of the mod (immersive-armors-1.1.3-forge.jar) fixed the incompatibility with First Aid, but now all armors type except the ones from this mod, doesn't render at all in the player model (both in inventory and outside of it), tho the stats work, it's only a visual issue from what i've tested so far. Here is a picture of the issue:

![armor](https://user-images.githubusercontent.com/90096585/167424824-e06aa0ba-1cb9-4245-b946-320e6087401e.jpg)

Forge version: 36.2.34

**Comment by Exokyhh** [comment]
Also, I found out that the Heavy Armor doesn't render correctly, it DOES render (unlike armors from other mods), but it's not correct, since Hats, Sleeves, and all the skin's parts, doesn't render and are "cut out" instead, leaving only the basic layer of the skin. For example, the gauntlets doesn't render and instead I see my hand with the top of the layer removed. Here's a pic:

![armor2](https://user-images.githubusercontent.com/90096585/167428440-09d914eb-f33b-4ef9-854b-c96883820e2d.png)

Hope I explained it correctly

**Comment by Luke100000** [comment]
First issue is a bug introduced with the cosmetic armor mod fix...
Second issue is not an issue, it blocks the second layer since it would overlap the armor. On the hand however it should still display, thanks.
If you do not like this, you can change that in the config file.

**Comment by Exokyhh** [comment]
Oh, thanks for explaining! I didn't know it was a config, btw, even if I turn off the cosmetic armor mod, the skins still appear to be invisible, don't know why

**Comment by Exokyhh** [comment]
I've literally tried removing all mods except this one, and it still has the issue, here's a pic:
![armor4](https://user-images.githubusercontent.com/90096585/167453298-ba379471-3f67-41a4-8093-1e88a048617e.PNG)

Forge - 36.2.34 (1.16.5)
immersive-armors-1.1.3-forge.jar

**Comment by Luke100000** [comment]
It's definitely an issue on my side, I'm already testing and will release in a few minutes :)

**Comment by Exokyhh** [comment]
Wish others mod developers could be like you, I love your work! Keep it up :D

**Comment by Luke100000** [comment]
Thanks :D I'm glad you are helping me! If you have time, please try the 1.1.4 version on CurseForge before I upload the other MC versions too. Both issues "should" be fixed, and hopefully I didn't introduce another one.

**Comment by Exokyhh** [comment]
I did a quick test, and everything seems to works fine! ;)

**Comment by Luke100000** [comment]
Yes! Finally! Thanks again, and see you at the next issue! ^^
