### ISSUE TITLE
[Suggestion] Utility armours.

### ISSUE THREAD

**Issue by SecretSeptus** [Luke100000/ImmersiveArmors#32]
Considering each of the armours already added has a specific function, it is quite curious that all of them are essentially focused on combat. It would be more engaging if some were more useful in other conditions. Although most of those utility functions are most likely already covered by enchantments I personally would love some more thematically designed armour. Maybe a diving suit? I know Prismarine already speeds you in water but some form of less combat-oriented swimming suit would be interesting. Furthermore, I feel like both chest plate and leggings of steampunk armour would be more interesting if instead of increasing your melee damage, they would grant you other benefits. Increased reach is one such idea, especially when building. After all the most fall damage is taken when building or running away from fights, not while actively fighting.

**Comment by Luke100000** [comment]
Steampunk chestplate now shows a compass and clock in the Hud, and the leggings allows for double jump. I will close that suggestion as implemented but will keep the diving armor in mind for future versions :)
