### ISSUE TITLE
Enchanted Armor doesn't "Glow" (1.16.5)

### ISSUE THREAD

**Issue by Exokyhh** [Luke100000/ImmersiveArmors#33]
In the latest version (immersive-armors-1.1.4-forge.jar), when the armor is enchanted, it doesn't show the "glowing" effect, and instead looks like a normal one. I also am using a shader, not sure if it affects it

Forge Version: 36.2.34 (1.16.5)
Shader: ComplementaryShaders_v4.1.zip
immersive-armors-1.1.4-forge.jar

**Comment by Exokyhh** [comment]
Update: The shader shouldn't affect the glowing, since it works with other armors, it's just the armors from your mod

**Comment by Exokyhh** [comment]
Could you please backport the changes to 1.16.5? I would love to finally see my heavy armor glow

**Comment by Luke100000** [comment]
Sure. But I have to warn you, sometimes leggings glow when you have enchanted boots and vice versa. I spent hours to debug this but it seems like a Minecraft issue on how glint is rendered.

**Comment by Exokyhh** [comment]
Its fine, if one piece of armor is enchanted probably all of them are, so all will either be enchanted or default, so I don't care at all about it xD

**Comment by Luke100000** [comment]
Done!
