### ISSUE TITLE
[Error}

### ISSUE THREAD

**Issue by benio1394** [Luke100000/ImmersiveArmors#35]
I found incompatibility between fabric immersive armors 1.3.3 and 4 and so I heard you talking crap about minecraft combat i difficulty. Crash file does not appear, only information about exit code 1. I hope it is possible to fix that

**Comment by Luke100000** [comment]
Without error I can't fix it. Double check the latest.txt and debug.txt files.

**Comment by benio1394** [comment]
Ok, I found crash report in logs: https://pastebin.com/EW8X7bk6

**Comment by Luke100000** [comment]
Awesome, thanks!
