### ISSUE TITLE
Compability with Guard villagers?

### ISSUE THREAD

**Issue by SireAwfulThe1st** [Luke100000/ImmersiveArmors#36]
Hey Luke, IW as wondering if you could fix the weird bug/incompability with the models of the guard villagers from Guard villagers mode?
 While this bug is mostly harmless cuz it only shows a visual bug where due tae the taller head model of the guard villagers, most of the armor pieces for head would have the slight top half of the villager head clips through the model.
 I was thinking if you could fix it for aesthetic purposes so the guard villagers would fit nicely with the nice design of the armors you made on your immersive armors mod! And it's also because I'd love tae play around with the guard villagers vs illagers using the armors from your mod. 
Perhaps you could consider adding compabilities with it and fix the visual bugs?
Thanks for looking at my issue, hope you'd consider this soon!

**Comment by Luke100000** [comment]
I played around for a while but came to the conclusion that it's too much work to fix. In general, every entity with a custom armor model won't work.
