### ISSUE TITLE
Add Configuration to Armor Properties

### ISSUE THREAD

**Issue by Rythox** [Luke100000/ImmersiveArmors#38]
[Suggestion] Make the armor abilities configurable, i.e. being able to change how long the wither armor's effect lasts or edit the explosion resistance amount from slime armor.

**Comment by Luke100000** [comment]
I will start rewriting code to enable more detailed configuration. Do you think it's sufficient to modify/disable existing effects, or do you want to be able to fully define which effects are present on what armor? The later is more work, and does not always work (some effects are armor specific).
