### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by ardissaps** [Luke100000/ImmersiveArmors#39]
Hello thank you for your time making this awesome mod!

There are some mods that does not work with Immersive Armor :
- [Show me your Skin](https://modrinth.com/mod/show-me-your-skin) (Adjust armor transparency)
- [DyeAllTheThing](https://modrinth.com/mod/dyeallthethings) (only Immersive Armor can't be dyed currently, other modded can, that mod is actually make undyeable armor become dyeable)

**Comment by Luke100000** [comment]
Thanks for the kind words!
Both are maybe won't fixes because I use custom models, and the mods mentioned works best on vanilla models only.  IA also has some custom dyeing stuff. I will leave this issue open in case I find a way to restore compatibility.

**Comment by Fourmisain** [comment]
Hey, Dye All The Things dev here, I [added compatibility](https://github.com/Fourmisain/DyeAllTheThings/issues/1) for your mod so you can scratch it from your list!

**Comment by Luke100000** [comment]
> Hey, Dye All The Things dev here, I [added compatibility](https://github.com/Fourmisain/DyeAllTheThings/issues/1) for your mod so you can scratch it from your list!

Awesome work, thanks!

**Comment by Luke100000** [comment]
I won't fix the transparency issue, I hope its not too big of a deal
