### ISSUE TITLE
Compatibiltiy issue in 1.16.5 version involving MixinEnchantmentHelper

### ISSUE THREAD

**Issue by ChrysanthCow** [Luke100000/ImmersiveArmors#41]
MixinEnchantmentHelper's Overwrite annotation may be completely unnecessary at this point in time for the 1.16.5 version of the mod.

Fixing this would fix compatibility between our two mods (my mod being Apugli) for this version of the game, as I Redirect into an expression that is completely overwritten in this mod and results in a crash.

**Comment by ChrysanthCow** [comment]
aaa I think I pinged people within my initial post, Unreal Engine repo type beat.

**Comment by Luke100000** [comment]
Thanks! I'm not very experienced regarding mixins :)
