### ISSUE TITLE
Adding Immersive Armors breaks other modded armors' textures?

### ISSUE THREAD

**Issue by pintachu** [Luke100000/ImmersiveArmors#5]
Was testing a Mod pack one mod at a time to find issue 
Mods installed and all were rendering:

- Alex's Mobs (dependency of Citadel)
- Floral Enchantment
- VIllage Employment
- Curios API (Forge)
- Cosmetic Armor Reworked
- Backpacked

As soon as I installed, the other mods no longer show on the player and show as a pink or pink/black box. Immersive armors would show on player.
Was just on a superflat creative world.

**Comment by Luke100000** [comment]
from other Report: Twilight Forest, Ice and Fire, Nautilium, Create, Atumnity and Yurina's Enderite Mod

**Comment by Luke100000** [comment]
Cosmetic Armor works for me, can you specify the incompatibility with it?

**Comment by Luke100000** [comment]
I tracked down this issue, will get fixed soon, thanks for the reports!

**Comment by pintachu** [comment]
So sorry I didn't check this yesterday, my dear mod author! First, THANK YOU for the mod, I really love it. Thank you for caring to bug fix!

**Comment by pintachu** [comment]
> Cosmetic Armor works for me, can you specify the incompatibility with it? Backpacked works fine too.

I apologize, those mods were working for me too, I just wanted to include that they were installed in case they were the issue.
