### ISSUE TITLE
[Suggestion] Make armors able to be found in chests

### ISSUE THREAD

**Issue by FumpleWumper** [Luke100000/ImmersiveArmors#55]
In the base game, chests and barrels throughout the world already have a chance of having armor inside them, so why not being able to find armors from this mod as well? I recently made a modpack for myself and some friends that overhauled enchantments and combat, and at first Immersive Armors fit perfectly into the idea of every player making their own kit, but recently I've added a mod that improves loot depending on where you find it (Dungeons Difficulty), which makes it so depending if you find armor in dungeons in the nether or in the end, the armor will have an added buff like extra hearts or extra armor points, and now nobody uses the armors from this mod because they'd rather wear the buffed armor they looted.
It would be really great if the armors from this mod could also be found in chests so we could use them again, and I'm sure people that play with exploration modpacks would really like it as well!

**Comment by Luke100000** [comment]
I see. I will check out both loot and the mod mentioned.
I will link this to this suggestion here: #50
