### ISSUE TITLE
Artifacts HUD Problem

### ISSUE THREAD

**Issue by gitgunter** [Luke100000/ImmersiveArmors#72]
I am currently using Artifacts mod in my mod pack and when using the Flamingo artifact, the Flamingo bar overlaps on top of it.
![2023-01-13_12 39 20](https://user-images.githubusercontent.com/73723099/212395113-883de6b5-0526-41ce-91b0-8ef565ba9ff4.png)

**Comment by Luke100000** [comment]
Hmm, I probably did not reset the graphics settings, thanks for the report

**Comment by gitgunter** [comment]
> Hmm, I probably did not reset the graphics settings, thanks for the report

1.18.2 btw

**Comment by Luke100000** [comment]
Are you sure it's immersive Armors related? I do not introduce any bars and I do not modify the HUD unless you wear Steampunk armor.
