### ISSUE TITLE
[Bug 1.18.2] Steampunk Chestplate Compass and Clock

### ISSUE THREAD

**Issue by INooBTooMuch** [Luke100000/ImmersiveArmors#73]
When wearing the steampunk chestplate the compass and the clock don't work, the clock just shows day and the compass is always showing forward.

Forge : 40.2.0
Immersive Armors : 1.5.3

**Comment by Luke100000** [comment]
If you use Quark mod, see #64

**Comment by INooBTooMuch** [comment]
Sorry, I didn't see that one

**Comment by newclearNRG** [comment]
https://github.com/Luke100000/ImmersiveArmors/issues/64 gives 404 error

I'm assuming there was more info in https://github.com/Luke100000/ImmersiveArmors/issues/64 but now that it's gone, I may reopen a new issue to get that info available again as the problem still exists in 1.21.1 (NeoForge 21.1.235)
