### ISSUE TITLE
Error, forge dependency missing???

### ISSUE THREAD

**Issue by Zestari** [Luke100000/ImmersiveArmors#80]
All mods are working just fine and server boots up normally, but as soon as I tried to implement Immersive Armors for Forge 1.5.4, it suddenly is missing the Forge dependency?? I'm completely unsure as to how this is possible as all other mods work completely fine. 

I even tried versions prior such as 1.5.1 and got a completely different error, but more concerned with 1.5.4's error. Any fixes? Server is currently running Arclight_1_18_2_2168109 and Forge version is 40.1.85. Any help on this is appreciated! If you need more info, I will provide it.

Se below the log for the error. Server promptly crashes after [15Feb2023 07:39:57.276] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: forge

[latest (1).log](https://github.com/Luke100000/ImmersiveArmors/files/10740483/latest.1.log)

**Comment by Luke100000** [comment]
I built for Forge 40.2.0, I assume 40.1.85 is rejected as being too old

**Comment by Zestari** [comment]
Do we know if any of the previous versions would work? It's a shame that the older the modpack goes in version, the less stuff will be available ;;

Only reason we have the older version is simply because we have mods that can only run on 40.1.80+ versions but below 40.2.0+ versions. Make's for some frustrating instances when many modpacks we've wanted arent compatible and we cant update the pre-existing ones cause they dont have 40.2.0+ compatibility

**Comment by Luke100000** [comment]
40.2.0 is the recommended version, and its unlikely it will change anymore. I would try to convince the mods incompatible with that version to update.

Based on history https://github.com/Luke100000/ImmersiveArmors/commit/c58ac12d0a10e3356e44a34475b64ddbaa036929 I updated forge a month ago, and 1.5.2 and below should work.

Ofc you can just hack your way through and just rip out the mod requirement in the mods.toml directly in the jar. Maybe immersive armors is compatible with older forge versions.
