### ISSUE TITLE
Installing mod in server crashes it

### ISSUE THREAD

**Issue by PzmuV1517** [Luke100000/ImmersiveArmors#85]
Hi, I want to install this mod on my server and I saw from your curse forge page that there are no needed dependencies so I just put the file raw on my client and on my server. The client works fine but the server crashes. I confirmed that it is the problem by deleting it and starting the server again. 

What should I do?

**Comment by PzmuV1517** [comment]
Sorry I saw that it is a copy of #81 I will close the issue..... ;)

**Comment by Luke100000** [comment]
Since so many people use some Bukkit implementation I will probably try to at least avoid a crash. I made an attempt last version but it apparently didn't work :)
