### ISSUE TITLE
Recipe for Immersive Armors

### ISSUE THREAD

**Issue by ImWhiff** [Luke100000/ImmersiveArmors#86]
Hello,

I wanted to change the recipe and value of some of the armors. I found out I can change the values through the config, but not the recipe. I downloaded the zip file of the source code and changed it from there; however, when I tried to gradlew build it and make a new lib, it showed an error. 

This is how I usually modify most mods to my liking, but for Immersive Armors, I am not able to unfortunately. Is there a way where I can change the recipe of the armors? (e.g., changing bone armors recipe to be crafted from bone blocks instead of just bone).

Thank you and for the awesome mod,
ImWhiff

![oudated loom](https://user-images.githubusercontent.com/122458396/236184358-97d0dc77-a8f9-4fed-a6da-0e0924da2f62.png)

**Comment by Luke100000** [comment]
Hi, this happens because I assumed everyone has git installed. I will add a fallback for that soon as you are not the only one who stumbled across this :)

For recipes I recommend a data pack, which is the intended way and does not require a recompile. It also survives updates and version changes.

**Comment by ImWhiff** [comment]
Hey, I tried doing it by creating a datapack. It did create the new recipe but the old recipe remained resulting 2 recipes for the same item. (E.g., bone boots can be created with bone blocks as well as normal bones)

**Comment by Luke100000** [comment]
Huh weird, it should replace the recipe. Make sure that both namespace (immersive_aircraft) and file name matches.

**Comment by ImWhiff** [comment]
Oh yeap. That was it. I matched the file name and now it's working as intended.
Thank you!
