### ISSUE TITLE
Changing durabilityMultiplier through config

### ISSUE THREAD

**Issue by ImWhiff** [Luke100000/ImmersiveArmors#87]
Hello, I was changing the values of some of the armours, and I was able to change protection, toughness, and weight just fine. Changing durability does not do anything, however. Even in the logs, it does not show it as error .
  
 I typed the durability values like this:
  
  "overwriteValues": {
    "heavy:helmetProtection": 3.0,
    "heavy:chestplateProtection": 7.0,
    "heavy:leggingsProtection": 6.0,
    "heavy:bootsProtection": 3.0,
    "heavy:durabilityMultiplier": 30.0,
    "heavy:toughness": 2.0
  },  

Edit: Not an issue for me anymore as I have found the way to clone the repository, edit the attributes, and build the jar file using git. But changing the attribute using the config file is still not functioning as intended so ig I will leave it open.

**Comment by Luke100000** [comment]
I looked into that, durability is a somewhat hardcoded feature of Mojang and can not be changed during runtime. Since server config sync is runtime, it thus does not work. I removed it from the doc.
