### ISSUE TITLE
Incompatible With Show Me Your Skin

### ISSUE THREAD

**Issue by PolyframeX** [Luke100000/ImmersiveArmors#90]
Version: 1.19.2
Modloader: Fabric 0.14.21
Mod Version: 1.5.5

When using show me your skin, armor is not able to be adjusted at all such as been hidden or transparent.

![image](https://github.com/Luke100000/ImmersiveArmors/assets/80133652/2cb252c0-f05d-4828-b069-eaaedd28910b)

Note:
I can understand if transparency is not possible, but it would be nice to have the ability to hide the armor at least.

**Comment by Luke100000** [comment]
Might be solved with #91, if it still happens after that please reopen

**Comment by PolyframeX** [comment]
Sorry to bother, but this issue has not been resolved.

**Comment by PolyframeX** [comment]
Sadly this has not fixed the issue.
