### ISSUE TITLE
[Enhancement] Migrate Fabric armor rendering to custom armor renderer

### ISSUE THREAD

**Issue by Linguardium** [Luke100000/ImmersiveArmors#91]
Fabric API has a built in hook for custom armor renderers. Looking at your code, it appears many of your mixins (that would conflict with geckolib occasionally) are unnecessary if you do this.

net.fabricmc.fabric.api.client.rendering.v1.ArmorRenderer

register it with ArmorRenderer.register(YOUR_RENDERER, YOUR_ITEM)

**Comment by Luke100000** [comment]
thanks for letting me know!
