### ISSUE TITLE
[1.20.1] Downgrade to 47.1.3? - TTF incompatibility

### ISSUE THREAD

**Issue by Toma400** [Luke100000/ImmersiveArmors#93]
When I tried running the game with Immersive Armors, notification that 47.1.3 is outdated came up. It would be absolutely fine in regular context, but considering current Forge situation, I'd ask if it could be possible to expand versioning for the mod to previous ones?

I have not much of idea what happens with Forge, but from what I've heard, any version after 47.1.3 are considered unstable by some developers I have contact with - apparently by Lex accepting many PRs after Forge team migrated onto NeoForge.
No idea if this is true, but at least one mod (The Twilight Forest) locked itself on version 47.1.3 and is currently not moving from there. So basically requiring later versions of Forge makes IA not compatibile with TTF purely by Forge version differences.

I hope this is taken in consideration and won't be problematic, because I really would love to play with both mods - IA seems like perfect complementary mod for my modpack. But yet, TTF is one of priority mods and I can't get away without it.

**Comment by Luke100000** [comment]
I just built for the most recent version and did not care about specifying ranges manually because I thought this would only result in a warning. I assume it makes sense to relax that condition. For now you can edit the meta-inf/mods.toml file until I pushed an update for that.

**Comment by Toma400** [comment]
Thank you so much, just downloaded the update! ^^
