### ISSUE TITLE
Russian translation doesn't work (1.20.1)

### ISSUE THREAD

**Issue by mpustovoi** [Luke100000/ImmersiveArmors#98]
Russian translation doesn't apply on anything from the mod.
I'm using version 1.6.1 for Fabric 1.20.1
![image](https://github.com/Luke100000/ImmersiveArmors/assets/92390626/1c8fb6b5-6422-4f2e-accc-34f07074a84f)
Maybe ru_ru.json is corrupted.

**Comment by Luke100000** [comment]
It works fine for me. Double check that you selected Russian and not Russian (Pre-revolutionary), and if that is fine please send the log to check for suppressed errors.

**Comment by mpustovoi** [comment]
Double checked that I definitely have not pre-revolutionary Russian.
Here's the log.
[latest.log](https://github.com/Luke100000/ImmersiveArmors/files/12499569/latest.log)
Maybe the problem is that I have about 400 mods…? 🧐
Although, recently the translation in your mod worked fine. However, after one of my modpack updates via Modrinth, the translation suddenly disappeared, and noteworthy that only in your mod.

**Comment by Luke100000** [comment]
Very weird. `languagereload` is the only mod I would guess having an influence on language loading at all, and Armors is using a classic asset pack for languages so this should not be an issue.

Btw your physics mod is suffering, it probably degrades your performance a bit when it keeps throwing exceptions like that.

**Comment by mpustovoi** [comment]
It's really very weird.
Especially because I just downloaded the mod file again and everything worked fine!
The problem was a comma instead of double quotes at the end of ru_ru.json, which literally came from nowhere. I really wonder where.
Thus, I close this phantom issue.

As for physics mod, I have 40-50 fps with Complementary Shaders.
Just took a look at the errors and… I can't parse them for myself.
Yep, there used to be crashes due to a ragdoll creation error for some mobs deep down in a caves, but now they seem to be gone.
